### ISSUE TITLE
Add Random Blook Generater

### ISSUE THREAD

**Issue by Justiniscoding** [RedYetiDev/blooket.js#4]
I recommend adding a get random blook function for anyone who cannot decide. for example you can use:
```
var blooks = ‘Chick Chicken Cow Goat Horse Pig Sheep Duck Dog Cat Rabbit Goldfish Hamster Turtle Kitten Puppy Bear Moose Fox Raccoon Squirrel Owl Hedgehog Tiger Orangutan Cockatoo Parrot Anaconda Jaguar Macaw Toucan Panther Capuchin Snowy_Owl Polar_Bear Artic_Fox Baby_Penguin Penguin Arctic_Hare Seal Walrus Witch Wizard Elf Fairy Slime_Monster Jester Dragon Queen Unicorn King Two_of_Spades Eat_Me Drink_Me Alice Queen_of_Hearts Dormouse White_Rabbit Cheshire_Cat Caterpillar Mad_Hatter King_of_Hearts Toast Cereal Yogurt Breakfast_Combo Orange_Juice Milk Waffle Pancakes French_Toast Pizza Earth Meteor Stars Alien Planet UFO Spaceship Astronaut Snow_Globe Holiday_Gift Hot_Chocolate Holiday_Wreath Gingerbread_Man Gingerbread_House Snowman Santa_Claus Pumpkin Swamp_Monster Frankenstein Vampire Zombie Mummy Werewolf Ghost Red_Astronaut Blue_Astronaut Green_Astronaut Pink_Astronaut Orange_Astronaut Yellow_Astronaut Black_Astronaut Purple_Astronaut Brown_Astronaut Cyan_Astronaut Lime_Astronaut Spooky_Pumpkin Spooky_Mummy Spooky_Ghost Frost_Wreath Tropical_Globe’;
blooks.replace(/_/g,’ ’);
blooks.split(‘ ’);
function random_blook(){
	var blook_number = Math.floor(Math.random * blooks.length);
	return blooks[blook_number]
}
```
sorry for the special apostrophes

**Comment by RedYetiDev** [comment]
I could implement something like this. I would need to change a few things so that if someone already has the blook, it will not choose that one.

**Comment by Justiniscoding** [comment]
i just added the global part to the replace function, and what do you mean by: 

> I could implement something like this. I would need to change a few things so that if someone already has the blook, it will not choose that one.
what do you mean by this?

**Comment by RedYetiDev** [comment]
Let's say you chose the Chicken Blook. And when I uses the random blook function, I landed on Chicken Blook, what would happen is some of your data would also be under by Blook. For example, swapping. Here is the transmitted data for each swap. 
`{"t":"d","d":{"r":1,"a":"p","b":{"p":"/PIN/c/NAME","d":{"at":"DISPLAYNAME:DISPLAYANIMAL:swap","b":"TARGETANIMAL","g": REMAINING}}}}`
The `TARGETANIMAL` would be 2 players, hence messing with the game.

**Comment by Justiniscoding** [comment]
That makes sense, you would mess up the game. do you have a plan on modifying this?

**Comment by Justiniscoding** [comment]
you may have to use a variable, but that will not be the best experience for users

**Comment by RedYetiDev** [comment]
My idea is after the client connects the websocket, but before it joins the game, It will do a player scan, and removes the found Blooks from the randomizer.

**Comment by RedYetiDev** [comment]
I have added this to the latest version
